name: MLE
channels:
  - defaults
dependencies:
  - ca-certificates=2024.3.11
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.8.19
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - appnope==0.1.4
      - asttokens==2.4.1
      - backcall==0.2.0
      - comm==0.2.2
      - cramjam==2.8.3
      - debugpy==1.8.1
      - decorator==5.1.1
      - executing==2.0.1
      - fastparquet==2024.2.0
      - fsspec==2024.3.1
      - importlib-metadata==7.1.0
      - ipykernel==6.29.4
      - ipython==8.12.3
      - jedi==0.19.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - matplotlib-inline==0.1.6
      - nest-asyncio==1.6.0
      - numpy==1.24.4
      - packaging==24.0
      - pandas==2.0.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - platformdirs==4.2.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==15.0.2
      - pygments==2.17.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyzmq==25.1.2
      - six==1.16.0
      - stack-data==0.6.3
      - tornado==6.4
      - traitlets==5.14.2
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - wcwidth==0.2.13
      - zipp==3.18.1
      - scipy==1.10.1
      - spacy==2.3.7